---

- name: 'Remove default config' 
  file:
    path: '/opt/service-two-epam/src/main/resources/application.yml'
    state: 'absent'
    
- name: 'Copy modifyed config' 
  copy:
    src: '/home/arsen/project-ansible-2/roles/role-service-two/templates/application.yml'
    dest: '/opt/service-two-epam/src/main/resources/'

- name: 'Maven clean package'
  command: 'sudo mvn -f /opt/service-two-epam/pom.xml clean package'

- name: 'Copy service'
  copy:
    src: '/home/arsen/project-ansible-2/roles/role-service-two/templates/service2.service'
    dest: '/lib/systemd/system'
    owner: root
    group: root

- name: 'Enable/Start Service'
  systemd:
    name: 'service2'
    daemon_reload: yes
    enabled: yes
    state: 'started'